generalResponse = "我是Beseye aisage bot, 您好"
greeting = "歡迎使用aisage bot" 
intro = "輸入\"介紹\" 進行功能導覽"
helpMessage = "輸入\"開啟\"來接收偵測結果推播，輸入\"停止\"來停止推播功能"
Hi = "Hi, 歡迎使用aisage & Beseye bot"
joke = "發大財"
joke2 = "Knock knock"
